{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] pool started\n",
      "[MainProcess/INFO] performing 100 scenarios * 1 policies * 1 model(s) = 100 experiments\n",
      "[SpawnPoolWorker-1/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-2/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-3/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-6/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-4/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-8/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-5/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-7/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-15/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[SpawnPoolWorker-10/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-11/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-12/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-16/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-13/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-14/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-9/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-23/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-18/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[SpawnPoolWorker-21/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-17/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-20/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-19/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-22/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-24/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-26/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-30/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-25/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[SpawnPoolWorker-27/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-31/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-28/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-29/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n",
      "[SpawnPoolWorker-32/ERROR] ebola_model() got an unexpected keyword argument '14'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 386, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 49, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Emma\\Anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 438, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "TypeError: ebola_model() got an unexpected keyword argument '14'\n"
     ]
    }
   ],
   "source": [
    "from model import ebola_model\n",
    "\n",
    "from ema_workbench import Model, IntegerParameter, RealParameter, TimeSeriesOutcome, ScalarOutcome, Policy\n",
    "\n",
    "model = Model('Ebola', function=ebola_model)\n",
    "\n",
    "model.uncertainties = [IntegerParameter('14', 1, 8),\n",
    "                       IntegerParameter('I14', 0, 5),\n",
    "                       IntegerParameter('I15', 25, 40),\n",
    "                       RealParameter('beta_i', 0.1, 0.5),\n",
    "                       RealParameter('travel_rate', 0.04, 0.1)]\n",
    "\n",
    "model.outcomes = [ScalarOutcome('Effectiveness'),\n",
    "                  ScalarOutcome('Speed'),\n",
    "                  ScalarOutcome('Equity in met demand'),\n",
    "                  ScalarOutcome('Equity in arrival times'),\n",
    "                  ScalarOutcome('Cost per death prevented')]\n",
    "\n",
    "model.levers = [RealParameter('exploration_ratio', 0.0, 1.0)]\n",
    "                \n",
    "policies = [Policy(\"All exploitation\", **{'exploration_ratio' : 0.0})]\n",
    "\n",
    "from ema_workbench import SequentialEvaluator\n",
    "\n",
    "from ema_workbench import ema_logging\n",
    "\n",
    "ema_logging.log_to_stderr(ema_logging.INFO)\n",
    "'''\n",
    "with SequentialEvaluator(model) as evaluator:\n",
    "    experiments, outcomes = evaluator.perform_experiments(scenarios=10, policies = policies)\n",
    "'''\n",
    "\n",
    "from ema_workbench import MultiprocessingEvaluator\n",
    "\n",
    "n_scenarios = 100\n",
    "\n",
    "import time\n",
    "start_time = time.time()\n",
    "\n",
    "\n",
    "with MultiprocessingEvaluator(model) as evaluator:\n",
    "    results = evaluator.perform_experiments(scenarios=100, policies = policies)\n",
    "    \n",
    "print(\"--- %s seconds ---\" % (time.time() - start_time))\n",
    "\n",
    "ema_workbench.util.utilities.save_results(results, test_run)\n",
    "    \n",
    "experiments, outcomes = results\n",
    "import matplotlib.pyplot as plt    \n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "\n",
    "policies = experiments['policy']\n",
    "\n",
    "data = pd.DataFrame.from_dict(outcomes)\n",
    "data['policy'] = policies\n",
    "\n",
    "sns.pairplot(data, hue='policy',  vars=outcomes.keys(), )\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
